services:
  backend-for-frontend:
    build:
      context: ${SERVICE_PATH:-services}/backend-for-frontend-python
      dockerfile: Dockerfile
    image: backend-for-frontend-python:latest
    ports:
      - "10115"
    environment:
      - OTEL_SERVICE_NAME=backend-for-frontend
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io:443
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=hcaik_01jekqdnx4hfk4xchx92771p1z0pbk79t301dnwkxxd9ye2qdbj04asxwe
      #^^bad practice to hardcode, do as i say not as i do?

  image-picker:
    build:
      context: ${SERVICE_PATH:-services}/image-picker-python
      dockerfile: Dockerfile
    image: image-picker-python:latest
    ports:
      - "10116"
    environment:
      BUCKET_NAME: random-pictures

  meminator:
    build:
      context: ${SERVICE_PATH:-services}/meminator-python
      dockerfile: Dockerfile
    image: meminator-python:latest
    ports:
      - "10117"
    environment:
      - OTEL_SERVICE_NAME=meminator
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io:443
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=hcaik_01jekqdnx4hfk4xchx92771p1z0pbk79t301dnwkxxd9ye2qdbj04asxwe
      #^^nothing to see here

  phrase-picker:
    build:
      context: ${SERVICE_PATH:-services}/phrase-picker-python
      dockerfile: Dockerfile
    image: phrase-picker-python:latest
    ports:
      - "10118"

  web:
    build:
      context: ${SERVICE_PATH:-services}/web
      dockerfile: Dockerfile
    image: web:latest
    #volumes: #lets go fast
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114"
    depends_on:
      backend-for-frontend:
        condition: service_started
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started
